# Generated by Django 4.2.3 on 2023-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('LE', 'Lenovo'), ('DE', 'Dell'), ('AC', 'Acer'), ('AS', 'Asus'), ('AP', 'Apple')], max_length=10)),
                ('manufacture_year', models.PositiveSmallIntegerField()),
                ('ram_amount_gb', models.PositiveSmallIntegerField()),
                ('hard_drive_capacity_gb', models.PositiveIntegerField()),
                ('price_rub', models.PositiveIntegerField()),
                ('stock_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
