# Generated by Django 4.2.3 on 2023-09-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('P', 'published'), ('NP', 'not published'), ('B', 'banned')], max_length=10)),
                ('category', models.CharField(choices=[('H', 'Hobby'), ('W', 'Work'), ('F', 'Family'), ('ND', 'Not defined')], max_length=10)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
