# Generated by Django 4.2.3 on 2023-10-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('H', 'Hobby'), ('W', 'Work'), ('F', 'Family')], max_length=10, null=True),
        ),
    ]
